Update Gitlab replacing FLOW mentions with CONVISO
convisoappsec/conviso-docs pull request #110
Opened 2022-10-24 18:29 UTC by tfrazao-ch

2022-11-08 20:41 UTC, GiovanniSM20 requested changes
Hoje ainda temos trechos no código que precisaríamos modificar para aceitar essa mudança.

2022-12-22 13:14 UTC, idan89 commented
@GiovanniSM20 quais seriam os que estão faltando? Pode enviar as mudanças aqui para revisarmos.

2022-12-22 14:08 UTC, GiovanniSM20 approved these changes

2023-01-26 20:36 UTC, andersonbosa requested changes
mudança só deve ser aprovada após concluirmos a atividade abaixo:

- [ ] [Adequação do nome Conviso no conviso-flowcli](https://app.clickup.com/t/3016679/DEV-2635)

2023-06-19 15:05 UTC, closed without merging