Azure update
convisoappsec/conviso-docs pull request #252
Opened 2023-09-14 18:35 UTC by gabogaldino

Atualização da vm image. build OK

cc @giovannism20

2023-09-14 19:20 UTC, giovannism20 requested changes

2023-09-14 19:20 UTC, giovannism20 commented on docs/integrations/azure-pipelines-cli.md
> -
Por que vamos tirar esse exemplo ?

2023-09-15 14:15 UTC, gabogaldino commented
O título é para SEO, colocando integration fica mais fácil para encontrar em pesquisa orgânica. A recomendação é que tenhamos "Integration" em todos os títulos, mas colocar isso no "label" vai ficar repetitivo e longo para quem estiver olhando o menu e label não tem tanto impacto em SEO quanto título.

2023-09-15 14:16 UTC, gabogaldino commented
Me guiando a partir desse doc https://docusaurus.io/pt-BR/docs/next/seo e das análises da Anathaly

2023-09-15 14:55 UTC, giovannism20 approved these changes

2023-09-15 14:55 UTC, giovannism20 commented on docs/integrations/codefresh.md
>  title: Codefresh
Faltou o Integration aqui

2023-09-15 14:55 UTC, giovannism20 commented on docs/integrations/jenkins-single-pipeline.md
> +title: Jenkins Single Pipeline
Faltou o Integration aqui

2023-09-15 14:55 UTC, merged