Add initial documentation for BusinessMap integration
convisoappsec/conviso-docs pull request #292
Opened 2024-03-01 12:02 UTC by paladini

# Description

Add documentation pages for BusinessMap integration.

Resulting documentation (please READ IT before approving):
![Screenshot_7-3-2024_115942_localhost](https://github.com/convisoappsec/conviso-docs/assets/3361224/baad670a-971d-4ecb-842e-960f4cd32638)

## Changes

- Add BusinessMap integration under "Defect Tracker" category of integrations;
- Add BusinessMap link in the sidebar;
- Add pictures from BusinessMap and Conviso Platform for the tutorial / article;

2024-03-01 20:46 UTC, eduardoconviso approved these changes

2024-03-04 12:10 UTC, dsmlucas approved these changes

2024-03-04 12:10 UTC, dsmlucas commented on docs/integrations/businessmap.md
> +The [Conviso Platform](https://cta-service-cms2.hubspot.com/web-interactives/public/v1/track/redirect?encryptedPayload=AVxigLKtcWzoFbzpyImNNQsXC9S54LjJuklwM39zNd7hvSoR%2FVTX%2FXjNdqdcIIDaZwGiNwYii5hX
A parte de comentários eu ainda deixaria sem mencionar, pois para o caso do businessmap não estamos disponibilizando ainda.

2024-03-04 17:15 UTC, paladini commented on docs/integrations/businessmap.md
> +The [Conviso Platform](https://cta-service-cms2.hubspot.com/web-interactives/public/v1/track/redirect?encryptedPayload=AVxigLKtcWzoFbzpyImNNQsXC9S54LjJuklwM39zNd7hvSoR%2FVTX%2FXjNdqdcIIDaZwGiNwYii5hX
Ah, eu havia usado o do Jira como base e esse esqueci trecho esqueci de remover/alterar para o caso de uso do BusinessMap. Boa observação!

2024-03-04 17:28 UTC, darenas-convisoappsec requested changes
Da uma olhada nesses comentários @paladini

2024-03-04 17:37 UTC, paladini commented on docs/integrations/businessmap.md
> +The [Conviso Platform](https://cta-service-cms2.hubspot.com/web-interactives/public/v1/track/redirect?encryptedPayload=AVxigLKtcWzoFbzpyImNNQsXC9S54LjJuklwM39zNd7hvSoR%2FVTX%2FXjNdqdcIIDaZwGiNwYii5hX
Okay! Eu peguei a base do artigo do Jira, que o Galdino fez, e comecei a modificar a partir dali pois já tinha uma base boa de passo-a-passo. Eu esqueci de modificar esse trecho e vou reformular algumas coisas pra ficar mais claro.

2024-03-04 17:38 UTC, paladini commented on docs/integrations/businessmap.md
> +This integration streamlines issue control management and vulnerability consolidation.
Okay! Vou remover esse termo e deixar mais claro os benefícios de uso da integração. Ele veio do artigo do Jira, mas acho que tem nos artigos de outras integrações de Defec Tracker também. É bom ser mais único para não ter várias integrações com textos similares.

2024-03-07 15:13 UTC, darenas-convisoappsec approved these changes
👍

2024-03-07 15:13 UTC, merged