adding sbom page
convisoappsec/conviso-docs pull request #357
Opened 2024-09-25 20:53 UTC by JAugusto42

2024-09-25 21:00 UTC, eduardoconviso commented on docs/tools/conviso-sbom/conviso-sbom.md
> +You need to pass the SBOM file in CycloneDX format, asset id and company id to be able to import a SBOM file.
import an SBOM file

2024-09-25 21:00 UTC, eduardoconviso commented on docs/tools/conviso-sbom/conviso-sbom.md
> +A SBOM file will be generated and sent to the respective asset each time you run `conviso ast run` or `conviso sca run`.
An SBOM file

2024-09-25 21:00 UTC, eduardoconviso commented on docs/tools/conviso-sbom/conviso-sbom.md
> +After run our AST, you can simply access the asset and you will find a Components section, just click in `View All`:
After running

2024-09-25 21:01 UTC, eduardoconviso commented on docs/tools/conviso-sbom/conviso-sbom.md
> +After run our AST, you can simply access the asset and you will find a Components section, just click in `View All`:
just click on

2024-09-27 01:00 UTC, darenas-convisoappsec requested changes
Adiciona uma explicação sobre CycloneDX

2024-09-30 12:52 UTC, darenas-convisoappsec requested changes
Tem algumas mudanças a serem feita ainda.

2024-09-30 12:52 UTC, darenas-convisoappsec commented on docs/tools/conviso-sbom/conviso-sbom.md
> +- **VEX**: Focuses on vulnerability exploitability data within SBOMs, helping prioritize vulnerabilities.
VEX não é um formato de SBOM. É um complemento/advisor para priorização de vulnerabilidades a partir do SBOM como input.

2024-09-30 12:52 UTC, darenas-convisoappsec commented on docs/tools/conviso-sbom/conviso-sbom.md
> +- **SWID**: ISO standard for identifying software assets installed on systems. Uses XML.
Não está muito claro o que é o SWID.

2024-10-01 04:11 UTC, JAugusto42 commented on docs/tools/conviso-sbom/conviso-sbom.md
> +- **VEX**: Focuses on vulnerability exploitability data within SBOMs, helping prioritize vulnerabilities.
fiquei um pouco confuso, o proprio CycloneDX coloca o vex como podendo ser um formato separado.
https://github.com/CycloneDX/bom-examples/tree/master/VEX
```VEX information can be represented inside an existing BOM, or in a dedicated VEX BOM```

2024-10-01 04:37 UTC, JAugusto42 commented on docs/tools/conviso-sbom/conviso-sbom.md
> +- **SWID**: ISO standard for identifying software assets installed on systems. Uses XML.
adicionei mais informacao

2024-10-01 04:40 UTC, JAugusto42 commented on docs/tools/conviso-sbom/conviso-sbom.md
> +- **VEX**: Focuses on vulnerability exploitability data within SBOMs, helping prioritize vulnerabilities.
por ele poder ser gerado separado, ou seja, por mais que dependa de um sbom (preferencialmente no formato CycloneDX) para ter a informacao completa, ele possui um formato proprio conhecido como VEX BOM, ai mantive ele ali na listagem, mas deixando claro que ele e um complemento ao sbom, apesar de ser possivel usar somante ele. Eu to usando esse material como referencia.
https://github.com/CycloneDX/bom-examples/tree/master/VEX

2024-10-01 13:38 UTC, darenas-convisoappsec approved these changes
👍

2024-10-01 16:29 UTC, merged